version: "3.3"
services:

  servicio-base-datos:
    image: carlosiribarren/listado-coches-bd:1.0.0-RELEASE
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=userCoches
      - POSTGRES_PASSWORD=passCoches
      - POSTGRES_DB=dbCoches

  servicio-back:
    image: carlosiribarren/listado-coches-api:1.0.1-RELEASE
    environment:
      - DB_URL=jdbc:postgresql://servicio-base-datos:5432/dbCoches
      - DB_SCHEMA=coches_schema
      - DB_USER=userCoches
      - DB_PASSWORD=passCoches      
    ports:
    - 8081:8081          

  servicio-front:
    image: carlosiribarren/listado-coches-web:1.0.1-RELEASE
    environment:
      - API_COCHES_HOST=http://servicio-back:8081        
    ports:
      - 8080:8080         


